export const genshinStickers = [

    {
        emotionTag: "calm",
        image: "AyakaCalm.png",
        alt: "A Ayaka sticker, calmly drinking some tea",
        region: "Inazuma",
        quote: "Snow that falls in the winter will inevitably melt in the spring. Everything will come to an end, and new things will come to take its place.",
    },
    {
        emotionTag: "Confident",
        image: "BeidouConfident.png",
        alt: "A Beidou sticker, confidently laughing",
        region: "Liyue",
        quote: "Only those who persevere can emerge victorious. Face forward, take the reins of your destiny, and make your way toward the future.",
    },
    {
        emotionTag: "Confident",
        image: "EulaConfident.png",
        alt: "A Eula sticker, giving you a thumbs up to provide you with confidence",
        region: "Mondstad",
        quote: "Vengeance will be mine! But until that day... let's dance!",
    },
    {
        emotionTag: "Confident",
        image: "JeanConfident.png",
        alt: "A Jean sticker, giving you a thumbs up to provide you with confidence",
        region: "Mondstad",
        quote: "As long as we live, we must stay true to ourselves.",
    },
    {
        emotionTag: "Brave",
        image: "KageroumaruBrave.png",
        alt: "A Kageroumaru sticker, very eerily and stoic like looking at you, giving you the courage to press on",
        region: "Inazuma",
        quote: "I am Kageroumaru, the sword that serves and protects. None shall harm my master while I still stand (woof woof).",
    },
    {
        emotionTag: "Pride",
        image: "KeqingPride.png",
        alt: "A cherfull Keqing sticker, happily looking at you with pride",
        region: "Liyue",
        quote: "I work tirelessly to bring about a better future. I have no regrets, no matter the hardships I face.",
    },
    {
        emotionTag: "Brave",
        image: "KleeBrave.png",
        alt: "A Klee sticker, cheering you on to keep going",
        region: "Mondstad",
        quote: "Everything is going to be fine. As long as we stick together, there's nothing to worry about!",
    },
    {
        emotionTag: "Confident",
        image: "KujouSaraConfident.png",
        alt: "A confident Kujou Sara sticker, giving out orders",
        region: "Inazuma",
        quote: "With every challenge, I grow stronger. There is no obstacle I cannot overcome with determination and skill.",
    },
    {
        emotionTag: "Pride",
        image: "MonaPride.png",
        alt: "A very proud Mona sticker",
        region: "Mondstad",
        quote: "Only those with the sharpest minds can grasp the secrets of the universe. Fortunately, you are one of them.",
    },
    {
        emotionTag: "Pride",
        image: "PaimonPride.png",
        alt: "A very proud and strong Paimon sticker, beware",
        region: "Mondstad",
        quote: "Paimon may be small, but Paimon can do big things! Just you watch!",
    },
    {
        emotionTag: "Confident",
        image: "Raiden ShogunConfident.png",
        alt: "A Raiden shogun sticker, sending off a bird",
        region: "Inazuma",
        quote: "You can be the blade that cuts through the darkness, guiding everyone towards a future of everlasting glory.",
    },
    {
        emotionTag: "Brave",
        image: "SayuBrave.png",
        alt: "A battle ready Sayu sticker",
        region: "Inazuma",
        quote: "Even if I'm small, I won't be scared! I'll face any challenge head-on and prove that size doesn't matter when it comes to bravery!",
    },
    {
        emotionTag: "Calm",
        image: "ThomaCalm.png",
        alt: "A calm Thoma sticker, with Kageroumaru sitting on top",
        region: "Inazuma",
        quote: "Peace is like the gentle breeze that rustles through the leaves, soothing the weary soul. In times of turmoil, it is important to find solace in the tranquility that surrounds us.",
    },
    {
        emotionTag: "Confident",
        image: "ThomaConfident.png",
        alt: "A confident Thoma sticker",
        region: "Inazuma",
        quote: "I may not have the strength of a warrior, but my resolve is unyielding. With unwavering determination, I will fulfill my duties and protect those who rely on me.",
    },
    {
        emotionTag: "Brave",
        image: "XianglingBrave.png",
        alt: "A Xiangling sticker cheering you on",
        region: "Liyue",
        quote: "Courage is like the flame that burns within us, guiding us through the darkest of times. With bravery in our hearts, there's nothing we can't overcome!",
    },
    {
        emotionTag: "Confident",
        image: "XinyanConfident.png",
        alt: "A confident Xinyan sticker, ready for action",
        region: "Inazuma",
        quote: "Rock 'n' roll is all about confidence, and I've got it in spades. When I'm on stage, nothing can shake me. I'm ready to rock the world!",
    },
    {
        emotionTag: "Calm",
        image: "YanfeiCalm.png",
        alt: "A calm Yanfei sticker, giving you advice",
        region: "Inazuma",
        quote: "In the eye of a storm, one must remain composed and steadfast. With careful consideration and diligence, justice will prevail.",
    },
    {
        emotionTag: "Confident",
        image: "YoimiyaConfident.png",
        alt: "A confident Yoimiya sticker, cheering you on",
        region: "Inazuma",
        quote: "Fireworks light up the sky, symbolizing our resolve and determination. With every explosion, we declare our unwavering confidence in our abilities and our commitment to achieving our goals!",
    },
    {
        emotionTag: "Calm",
        image: "ZhongliCalm.png",
        alt: "A calm Zhongli sticker, drinking tea",
        region: "Liyue",
        quote: "Like the mountains that stand firm against the winds, you can maintain a tranquil demeanor in the face of life's storms. Serenity is the key to enduring all trials.",
    },
    {
        emotionTag: "Confident",
        image: "ArlechinoCalm.png",
        alt: "A calm Arlechino, sitting upon a throne",
        region: "Fontaine",
        quote: " Fear not. What's a little thunder when even a storm wouldn't stop you in your tracks.",
    },
    {
        emotionTag: "Pride",
        image: "FurinaProud.png",
        alt: "A proud Furina",
        region: "Fontaine",
        quote: " Why are you just standing there with your mouth gaping? Ah, you must be stunned and at a loss for words... Understandable, it is I after all....",
    },
    {
        emotionTag: "Calm",
        image: "TighnariCalm.png",
        alt: "A calm Tighnari",
        region: "Sumeru",
        quote: "Whoever or wherever you are, I am certain that you will succeed, please keep it up",
    },
    {
        emotionTag: "Calm",
        image: "XiaoCalm.png",
        alt: "A calm Xiao",
        region: "Sumeru",
        quote: "In the midst of chaos, find solace in the stillness of your heart. Only then can you truly understand the nature of tranquility.",
    },
    {
        emotionTag: "Calm",
        image: "NinguangCalm.png",
        alt: "A calm Ninguang",
        region: "Liyue",
        quote: "Amidst the chaos, there lies a serene center. It is there, in the calm, that clarity and wisdom are found.",
    },
    {
        emotionTag: "Calm",
        image: "KokomiCalm.png",
        alt: "A calm Kokomi",
        region: "Inazuma",
        quote: "Like the steady flow of a river, let your mind drift calmly. In serenity, clarity emerges, and solutions reveal themselves.",
    },
    {
        emotionTag: "Brave",
        image: "KazuhaBrave.png",
        alt: "Kazuha noding at you",
        region: "Inazuma",
        quote: "Embrace the unknown with courage, for it is in the face of adversity that true strength is forged. I will navigate these turbulent waters and emerge victorious!",
    },
]

