export const genshinStickers = [

    {
        emotionTag: "calm",
        image: "stickers/AyakaCalm.png",
        alt: "A Ayaka sticker, calmly drinking some tea",
        region:"Inazuma",
        quote:,
    },
    {
        emotionTag: "Confident",
        image: "stickers/BeidouConfident.png",
        alt: "A Beidou sticker, confidently laughing",
        region:,
        quote:,
    },
    {
        emotionTag: "Confident",
        image: "stickers/EulaConfident.png",
        alt: "A Eula sticker, giving you a thumbs up to provide you with confidence",
        region:,
        quote:,
    },
    {
        emotionTag: "Confident",
        image: "stickers/JeanConfident.png",
        alt: "A Jean sticker, giving you a thumbs up to provide you with confidence",
        region:,
        quote:,
    },
    {
        emotionTag: "Brave",
        image: "stickers/KageroumaruBrave.png",
        alt: "A Kageroumaru sticker, very eerily and stoic like looking at you, giving you the courage to press on",
        region:,
        quote:,
    },
    {
        emotionTag: "Pride",
        image: "stickers/KeqingPride.png",
        alt: "A cherfull Keqing sticker, happily looking at you with pride",
        region:,
        quote:,
    },
    {
        emotionTag: "Brave",
        image: "stickers/KleeBrave.png",
        alt: "A Klee sticker, cheering you on to keep going",
        region:,
        quote:,
    },
    {
        emotionTag: "Confident",
        image: "stickers/KujouSaraConfident.png",
        alt: "A confident Kujou Sara sticker, giving out orders",
        region:,
        quote:,
    },
    {
        emotionTag: "Pride",
        image: "stickers/MonaPride.png",
        alt: "A very proud Mona sticker",
        region:,
        quote:,
    },
    {
        emotionTag: "Pride",
        image: "stickers/PaimonPride.png",
        alt: "A very proud and strong Paimon sticker, beware",
        region:,
        quote:,
    },
    {
        emotionTag: "Confident",
        image: "stickers/Raiden ShogunConfident.png",
        alt: "A Raiden shogun sticker, sending off a bird",
        region:,
        quote:,
    },
    {
        emotionTag: "Brave",
        image: "stickers/SayuBrave.png",
        alt: "A battle ready Sayu sticker",
        region:,
        quote:,
    },
    {
        emotionTag: "Calm",
        image: "stickers/ThomaCalm.png",
        alt: "A calm Thoma sticker, with Kageroumaru sitting on top",
        region:,
        quote:,
    },
    {
        emotionTag: "Confident",
        image: "stickers/ThomaConfident.png",
        alt: "A confident Thoma sticker",
        region:,
        quote:,
    },
    {
        emotionTag: "Brave",
        image: "stickers/XianglingBrave.png",
        alt: "A Xiangling sticker cheering you on",
        region:,
        quote:,
    },
    {
        emotionTag: "Confident",
        image: "stickers/XinyanConfident.png",
        alt: "A confident Xinyan sticker, ready for action",
        region:,
        quote:,
    },
    {
        emotionTag: "Calm",
        image: "stickers/YanfeiCalm.png",
        alt: "A calm Yanfei sticker, giving you advice",
        region:,
        quote:,
    },
    {
        emotionTag: "Confident",
        image: "stickers/YoimiyaConfident.png",
        alt: "A confident Yoimiya sticker, cheering you on",
        region:,
        quote:,
    },
    {
        emotionTag: "Calm",
        image: "stickers/ZhongliCalm.png",
        alt: "A calm Zhongli sticker, drinking tea",
        region:,
        quote:,
    },
]
